version: "3"

services:
  wordpress_phpunit:
    image: "chriszarate/wordpress-phpunit:<%= phpUnitVersion %>"
    volumes:
      - "./src/wp:/app"
      - "testsuite:/tmp"
  mysql_phpunit:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""

volumes:
testsuite: {}
