version: "3"

services:

  wordpress:
    image: penskemediacorporation/wpserver
    working_dir: <%= wpDir %>/wp-content/themes/<%= wpTheme %>
    ports:
      - 80:80
    depends_on:
      - "mysql"
    networks:
      - "front"
      - "back"
    volumes:
      - "./.cache/images:<%= wpDir %>/wp-content/images"
      - "./.cache/languages:<%= wpDir %>/wp-content/languages"
      - "./.cache/private:<%= wpDir %>/wp-content/private"
      - "./.cache/uploads:<%= wpDir %>/wp-content/uploads"
      - "./.cache/wp:<%= wpDir %>:rw"
      - "./:<%= wpDir %>/wp-content/themes/<%= wpTheme %>:rw"
      - "./vendor/pmc/mu-plugins:<%= wpDir %>/wp-content/mu-plugins"
      - "./vendor/pmc/plugins:<%= wpDir %>/wp-content/plugins:rw"
      <% if(wpHasCoreV2) { %>- "./vendor/pmc/themes/vip/pmc-core-v2:<%= wpDir %>/wp-content/themes/vip/pmc-core-v2"<% } %>

  mysql:
    image: "mariadb"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
    networks:
      - "back"

  pipeline-build:
    image: penskemediacorporation/pipeline-build:v2
    working_dir: <%= wpDir %>/wp-content/themes/<%= wpTheme %>
    env_file: .env
    volumes:
      - "./.cache/wp:<%= wpDir %>:rw"
      - "./:<%= wpDir %>/wp-content/themes/<%= wpTheme %>:rw"
      - "./confd-configs:/etc/confd"
      - "./vendor/pmc/mu-plugins:<%= wpDir %>/wp-content/mu-plugins"
      - "./vendor/pmc/plugins:<%= wpDir %>/wp-content/plugins:rw"
      <% if(wpHasCoreV2) { %>- "./vendor/pmc/themes/vip/pmc-core-v2:<%= wpDir %>/wp-content/themes/vip/pmc-core-v2"<% } %>
    networks:
      - "back"
    depends_on:
      - mysql

  pipeline-test:
    image: penskemediacorporation/pipeline-test:v2
    working_dir: <%= wpDir %>/wp-content/themes/<%= wpTheme %>
    env_file: .env
    volumes:
      - "./.cache/wp:<%= wpDir %>:rw"
      - "./:<%= wpDir %>/wp-content/themes/<%= wpTheme %>:rw"
      - "./confd-configs:/etc/confd"
      - "./vendor/pmc/mu-plugins:<%= wpDir %>/wp-content/mu-plugins"
      - "./vendor/pmc/plugins:<%= wpDir %>/wp-content/plugins:rw"
      <% if(wpHasCoreV2) { %>- "./vendor/pmc/themes/vip/pmc-core-v2:<%= wpDir %>/wp-content/themes/vip/pmc-core-v2"<% } %>

networks:
  back: {}
  front: {}

volumes:
  mysql: {}
