image:
  name: penskemediacorporation/pipeline-compose
  username: $DOCKERHUB_PIPELINE_USERNAME
  password: $DOCKERHUB_PIPELINE_PASSWORD
options:
  docker: true

pipelines:
  default:
    - step:
        name: Build & Test
        services:
          - docker
        caches:
          - composer
          - docker
          - node
        script:
          - . /usr/local/bin/docker-entrypoint.sh && build_and_test

definitions:
  services:
    docker:
      memory: 2048
