image:
  name: penskemediacorporation/pipeline-compose
  username: $DOCKERHUB_PIPELINE_USERNAME
  password: $DOCKERHUB_PIPELINE_PASSWORD
options:
  docker: true

pipelines:
  default:
    - step:
        name: Build
        services:
          - docker
        caches:
          - composer
          - composerlocal
          - docker
          - localcache
          - node
        script:
          - . /usr/local/bin/docker-entrypoint.sh && build
    - step:
        name: Test
        services:
          - docker
        caches:
          - composer
          - composerlocal
          - docker
          - localcache
          - node
        script:
          - . /usr/local/bin/docker-entrypoint.sh && test
<% if (wpHasSvnDeploy) { %>
    - step:
        name: Deploy to VIP SVN
        deployment: production
        trigger: manual
        image:
          name: penskemediacorporation/pipeline-deploy
          username: $DOCKERHUB_PIPELINE_USERNAME
          password: $DOCKERHUB_PIPELINE_PASSWORD
        script:
          - source /usr/local/bin/start.sh<% } %>

definitions:
  caches:
    composerlocal: vendor
    localcache: .cache
