version: "3"

services:

  wp:
    image: penskemediacorporation/wpdev
    env_file: .env
    working_dir: "<%= wpDir %>/wp-content/themes/$WP_THEME"
    depends_on:
      - "mysql"
    networks:
      - "back"
      - "traefik"
    labels:
      - 'traefik.enable=true'
      - "traefik.frontend.rule=Host:$WP_DOMAIN"
      - "traefik.docker.network=traefik"
    volumes:
      - "./.cache/wp:<%= wpDir %>:rw"
      - "./:<%= wpDir %>/wp-content/themes/$WP_THEME:rw"
      - "./confd-configs:/etc/confd"
      - "$PMC_SHARED_CODE_PATH/mu-plugins:<%= wpDir %>/wp-content/mu-plugins"
      - "$PMC_SHARED_CODE_PATH/plugins:<%= wpDir %>/wp-content/plugins:rw"
      <% if(wpHasParentTheme) { %>- "$PMC_SHARED_CODE_PATH/themes/vip/<%= wpParentTheme %>:<%= wpDir %>/wp-content/themes/vip/<%= wpParentTheme %>"<% } %>

  mysql:
    image: "mariadb"
    env_file: .env
    networks:
      - "back"

  pipeline-build:
    image: penskemediacorporation/pipeline-build
    env_file: .env
    working_dir: "<%= wpDir %>/wp-content/themes/$WP_THEME"
    volumes:
      - "./.cache/wp:<%= wpDir %>:rw"
      - "./:<%= wpDir %>/wp-content/themes/$WP_THEME:rw"
      - "$PMC_SHARED_CODE_PATH/mu-plugins:<%= wpDir %>/wp-content/mu-plugins"
      - "$PMC_SHARED_CODE_PATH/plugins:<%= wpDir %>/wp-content/plugins:rw"
      <% if(wpHasParentTheme) { %>- "$PMC_SHARED_CODE_PATH/themes/vip/<%= wpParentTheme %>:<%= wpDir %>/wp-content/themes/vip/<%= wpParentTheme %>"<% } %>
    networks:
      - "back"
    depends_on:
      - mysql

  pipeline-test:
    image: penskemediacorporation/pipeline-test
    env_file: .env
    working_dir: "<%= wpDir %>/wp-content/themes/$WP_THEME"
    volumes:
      - "./.cache/wp:<%= wpDir %>:rw"
      - "./:<%= wpDir %>/wp-content/themes/$WP_THEME:rw"
      - "$PMC_SHARED_CODE_PATH/mu-plugins:<%= wpDir %>/wp-content/mu-plugins"
      - "$PMC_SHARED_CODE_PATH/plugins:<%= wpDir %>/wp-content/plugins:rw"
      <% if(wpHasParentTheme) { %>- "$PMC_SHARED_CODE_PATH/themes/vip/<%= wpParentTheme %>:<%= wpDir %>/wp-content/themes/vip/<%= wpParentTheme %>"<% } %>

networks:
  traefik:
    external: true
  back: {}

volumes:
  mysql: {}
