image:
  name: penskemediacorporation/pipeline-compose
  username: $DOCKERHUB_PIPELINE_USERNAME
  password: $DOCKERHUB_PIPELINE_PASSWORD
options:
  docker: true

pipelines:
  default:
    - step:
        name: Build & Test
        services:
          - docker
        caches:
          - composer
          - docker
          - node
        script:
          - wget -O - https://raw.githubusercontent.com/penske-media-corp/alpine-wordpress/master/_ss/global/_ss-ci.sh | sh

definitions:
  services:
    docker:
      memory: 2048
