pipeline {
	agent any
	stages {
		stage('RUN CI') {
			steps {
				withCredentials([
						string(credentialsId: 'composer-auth', variable: 'COMPOSER_AUTH')
				]) {
					wrap([$class: 'AnsiColorBuildWrapper', 'colorMapName': 'xterm']) {
						sh script: 'wget --no-cache -O - https://raw.githubusercontent.com/penske-media-corp/alpine-wordpress/master/_ss/global/_ss-ci.sh | sh'
					}
				}
			}
		}
	}
}
